variables:
  REGISTRY_HOST: ipe-wim-gitlab.fzi.de:5000
  IMAGE_NAME: $REGISTRY_HOST/$CI_PROJECT_PATH/$CI_COMMIT_REF_NAME

stages:
   - build
   - docker
   - deploy

build:
  image: beevelop/nodejs-python
  stage: build
  script:
    - cd website/
    - export NODE_PATH=/cache/node_modules
    - npm install --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - website/build/streampipes-docs/**
    expire_in: 1 week


nginx:
  image: docker:17.06.0-ce
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $REGISTRY_HOST
    - docker build --pull --no-cache -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

deploy:
  image: arvindr226/alpine-ssh
  stage: deploy
  only: 
    - master
  script:
    - apk add sshpass
    - sshpass -V
    - export SSHPASS=$BOTY_PWD 
    - sshpass -e ssh boty@kalmar46.fzi.de 'bash -s' < /opt/streampipes-docs-new/deploy.sh


